# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.10"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install toml
  - python -c 'import toml; c = toml.load("pyproject.toml"); print("\n".join(c["project"]["dependencies"]));' | pip install -r /dev/stdin

# command to run tests, e.g. python setup.py test
script: make test
