[project]
name = "pyschematron"
description = "Schematron validation in Python."
readme = "README.rst"
version = "0.1.0"
requires-python = ">=3.10"
keywords = ["Schematron", "XML validation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.10",
]
license = { file="LICENSE" }
authors = [
    { name = "Robbert Harms", email = "robbert@xkls.nl" }
]
dependencies = [
    "xmlschema==2.2.3",
    "elementpath==4.1.1",
    "toml==0.10.2",
    "typer[all]==0.7.0",
    "appdirs==1.4.4",
    "lxml==4.9.2",
    "Jinja2==3.1.2",
    "ruyaml==0.91.0"
]

[project.optional-dependencies]
test = [
    "pytest==7.2.2",
    "pytest-cov==4.0.0",
    "pytest-html==3.2.0",
    "pytest-check==2.1.2",
    "tox==4.4.7"
]
doc = [
    "sphinx==6.1.3"
]

[project.scripts]
adf-validator = "pyschematron.cli:app"

[build-system]
requires = ["flit_core >=3.8,<4"]
build-backend = "flit_core.buildapi"
