[project]
name = "pyschematron"
description = "Schematron validation in Python."
readme = "README.rst"
version = "0.1.1"
requires-python = ">=3.11"
keywords = ["Schematron", "XML validation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3.11",
]
license = { file="LICENSE" }
authors = [
    { name = "Robbert Harms", email = "robbert@xkls.nl" }
]
dependencies = [
    "xmlschema==2.4.0",
    "elementpath==4.1.5",
    "typer[all]==0.9.0",
    "appdirs==1.4.4",
    "lxml==4.9.3",
    "Jinja2==3.1.2",
    "ruyaml==0.91.0"
]

[project.optional-dependencies]
test = [
    "pytest==7.4.2",
    "pytest-check==2.2.1",
    "pytest-cov==4.1.0",
    "pytest-html==4.0.2",
    "tox==4.11.3"
]
doc = [
    "sphinx==7.2.6"
]

[project.scripts]
adf-validator = "pyschematron.cli:app"

[build-system]
requires = ["flit_core >=3.9,<4"]
build-backend = "flit_core.buildapi"
